<#
.SYNOPSIS
    Generates the deterministic human-readable Terraform parity view.
#>
[CmdletBinding()]
param(
    [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path,
    [string]$InventoryPath = 'parity/inventory.json',
    [string]$OutputPath = 'docs/terraform-parity.md',
    [switch]$Check
)

Set-StrictMode -Version 3.0
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'Parity.Common.ps1')

function ConvertTo-MarkdownCell {
    param([AllowEmptyString()] [string]$Value)
    return $Value.Replace('\', '\\').Replace('|', '\|').Replace('<', '&lt;').Replace('>', '&gt;').Replace("`r", '').Replace("`n", '<br>')
}
function Join-MarkdownValues {
    param([object[]]$Values)
    if (@($Values).Count -eq 0) { return '—' }
    return ConvertTo-MarkdownCell (@($Values) -join '; ')
}
function ConvertTo-ContractJson {
    param($Value)
    return ConvertTo-MarkdownCell (ConvertTo-Json -InputObject $Value -Depth 100 -Compress)
}

try {
    $rootPath = Resolve-ParityPath -Root $Root -Path '.'
    $inventoryFile = Resolve-ParityPath -Root $rootPath -Path $InventoryPath -MustExist
    $outputFile = Resolve-ParityPath -Root $rootPath -Path $OutputPath
    $inventory = Read-ParityJson $inventoryFile
    $assessedAt = if ($inventory.baseline.assessedAt -is [datetime]) {
        $inventory.baseline.assessedAt.ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ', [Globalization.CultureInfo]::InvariantCulture)
    }
    else {
        [string]$inventory.baseline.assessedAt
    }
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add('# Terraform parity inventory')
    $lines.Add('')
    $lines.Add('> Generated from `parity/inventory.json`. Do not edit this file directly.')
    $lines.Add('')
    $lines.Add("Assessed at: ``$assessedAt``")
    $lines.Add('')
    $lines.Add("Baseline: Bicep ``$($inventory.baseline.source.releaseTag)`` at ``$($inventory.baseline.source.commitSha)``; Terraform ``$($inventory.baseline.terraform.releaseTag)`` at ``$($inventory.baseline.terraform.commitSha)``.")
    $lines.Add('')
    $lines.Add('## Interpretation')
    $lines.Add('')
    $lines.Add('- Each capability is assessed independently for `standalone-standard` and `standalone-network-isolated`.')
    $lines.Add('- Bicep standard means `deploymentMode=standalone` and `networkIsolation=false`: public access without mandatory VNet, private endpoints, firewall, Bastion, NAT, or private DNS.')
    $lines.Add('- Bicep network-isolated means `deploymentMode=standalone` and `networkIsolation=true`: VNet, private endpoints, firewall, Bastion, NAT, and private DNS.')
    $lines.Add('- Terraform `flag_platform_landing_zone=false` approximates only network-isolated standalone. Its required VNet/subnets/private endpoints and disabled-public-access defaults cannot represent standalone-standard.')
    $lines.Add('')
    $lines.Add('## Status and evidence')
    $lines.Add('')
    $lines.Add('- **full**: static source inspection found the capability; **partial**: only part is present; **absent**: no equivalent was found; **blocked**: target topology or provider structure prevents the scenario.')
    $lines.Add('- **static**, **proposal**, **merged**, **deployed**, and **reviewed** describe evidence maturity, not support.')
    $lines.Add('- `parityDeclared` stays false until the same scenario and target commit have both a successful deployment and an approved reviewed comparison. Plans and static checks never prove parity.')
    $lines.Add('- Input defaults use JSON-native values when `representation=literal`. `representation=expression` stores the exact compiled ARM expression, including its outer brackets; `representation=none` identifies a required input with no default.')
    $lines.Add('')
    $lines.Add('## Capability assessments')
    $lines.Add('')
    $lines.Add('| ID | Capability | Scenario | Status | Impact / blocked reason | Default differences | Evidence |')
    $lines.Add('| --- | --- | --- | --- | --- | --- | --- |')
    foreach ($capability in @($inventory.capabilities | Sort-Object id -Stable)) {
        foreach ($assessment in @($capability.scenarioAssessments | Sort-Object scenario -Stable)) {
            $impact = if ($assessment.supportStatus -eq 'blocked') { $assessment.blockedReason } else { $assessment.consumerImpact }
            $evidence = (@($capability.referenceEvidence) + @($capability.terraformEvidence)) -join '; '
            $lines.Add(('| `{0}` | {1} | `{2}` | **{3}** | {4} | {5} | {6} |' -f
                (ConvertTo-MarkdownCell $capability.id),
                (ConvertTo-MarkdownCell $capability.title),
                $assessment.scenario,
                $assessment.supportStatus,
                (ConvertTo-MarkdownCell $impact),
                (Join-MarkdownValues $assessment.compatibility.defaultDifferences),
                (ConvertTo-MarkdownCell $evidence)))
        }
    }
    $lines.Add('')
    $lines.Add('## Detailed source contract')
    $lines.Add('')
    $lines.Add('### Inputs')
    $lines.Add('')
    $lines.Add('| Name | Kind | Type representation | Type value | Required | Default representation | Default value / expression | Allowed values |')
    $lines.Add('| --- | --- | --- | --- | ---: | --- | --- | --- |')
    foreach ($inputContract in @($inventory.surfaceContracts.inputs | Sort-Object name -Stable)) {
        $typeValue = if ($inputContract.type.representation -eq 'built-in') { $inputContract.type.name } else { $inputContract.type.ref }
        $defaultValue = switch ($inputContract.default.representation) {
            'literal' { ConvertTo-ContractJson $inputContract.default.value }
            'expression' { ConvertTo-MarkdownCell $inputContract.default.expression }
            default { '—' }
        }
        $lines.Add(('| `{0}` | `{1}` | `{2}` | `{3}` | `{4}` | `{5}` | `{6}` | `{7}` |' -f
            (ConvertTo-MarkdownCell $inputContract.name),
            $inputContract.kind,
            $inputContract.type.representation,
            (ConvertTo-MarkdownCell $typeValue),
            ([string]$inputContract.required).ToLowerInvariant(),
            $inputContract.default.representation,
            $defaultValue,
            (ConvertTo-ContractJson @($inputContract.allowedValues))))
    }
    $lines.Add('')
    $lines.Add('### Outputs')
    $lines.Add('')
    $lines.Add('| Name | Kind | Type representation | Type value |')
    $lines.Add('| --- | --- | --- | --- |')
    foreach ($outputContract in @($inventory.surfaceContracts.outputs | Sort-Object name -Stable)) {
        $typeValue = if ($outputContract.type.representation -eq 'built-in') { $outputContract.type.name } else { $outputContract.type.ref }
        $lines.Add(('| `{0}` | `{1}` | `{2}` | `{3}` |' -f
            (ConvertTo-MarkdownCell $outputContract.name),
            $outputContract.kind,
            $outputContract.type.representation,
            (ConvertTo-MarkdownCell $typeValue)))
    }
    $lines.Add('')
    $lines.Add('### Runtime keys')
    $lines.Add('')
    $lines.Add('| Name | Kind | Classification | Pattern |')
    $lines.Add('| --- | --- | --- | --- |')
    foreach ($runtimeContract in @($inventory.surfaceContracts.runtimeKeys | Sort-Object name -Stable)) {
        $pattern = if ($runtimeContract.classification -eq 'pattern') {
            ConvertTo-MarkdownCell $runtimeContract.pattern
        }
        else {
            '—'
        }
        $lines.Add(('| `{0}` | `{1}` | `{2}` | `{3}` |' -f
            (ConvertTo-MarkdownCell $runtimeContract.name),
            $runtimeContract.kind,
            $runtimeContract.classification,
            $pattern))
    }
    $lines.Add('')
    $lines.Add('## Consumer surfaces')
    $lines.Add('')
    foreach ($capability in @($inventory.capabilities | Sort-Object id -Stable)) {
        $lines.Add("### ``$($capability.id)``")
        $lines.Add('')
        $lines.Add((@($capability.consumerSurfaces | Sort-Object) | ForEach-Object { "- ``$_``" }) -join [Environment]::NewLine)
        $lines.Add('')
    }
    $lines.Add('## Exclusions')
    $lines.Add('')
    $lines.Add('- Terraform source and patches are excluded from this repository.')
    $lines.Add('- Hub-integrated Bicep and Terraform platform-landing-zone scenarios are outside this two-scenario baseline.')
    $lines.Add('- Static source inspection does not establish deployed runtime parity.')
    $lines.Add('')
    $lines.Add('## Baseline advancement')
    $lines.Add('')
    $lines.Add('Under [proposed ADR-0006](adr/0006-release-metadata-and-comparison-baselines.md), release metadata is independent of this historical comparison. Advancing `parity/config.json` and `parity/inventory.json` requires a separate reviewed change, complete surface coverage, regeneration of this document, and explicit treatment of historical record references. A manifest version bump neither advances these pins nor rewrites records, approvals, handoffs or digests; never follow a moving branch or tag silently.')
    $content = ($lines -join "`n") + "`n"

    if ($Check) {
        if (-not (Test-Path -LiteralPath $outputFile -PathType Leaf) -or [IO.File]::ReadAllText($outputFile) -cne $content) {
            Throw-ParityError "Generated parity Markdown is out of date: $outputFile" 'ParityMarkdownDrift'
        }
        Write-Host "Generated parity Markdown is current: $outputFile"
    }
    else {
        Write-ParityFileAtomic -Path $outputFile -Content $content
        Write-Host "Generated parity Markdown: $outputFile"
    }
    exit 0
}
catch {
    Write-Error $_
    exit 1
}
