# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json
name: azure-ai-lz
metadata:
  template: azure-ai-lz
infra:
  provider: bicep
  path: .
  module: main
hooks:
  preprovision:
    posix:
      shell: pwsh
      run: ./scripts/Invoke-PreflightChecks.ps1
      continueOnError: false
      interactive: true
    windows:
      shell: pwsh
      run: ./scripts/Invoke-PreflightChecks.ps1
      continueOnError: false
      interactive: true